In [1]:
# loading required library

import pandas as pd
import numpy as np

I will be using the credit card application dataset, where I will try to predict whether or not a given customer should be approved for their credit application.

In [2]:
# Read the file 

cred_Data = pd.read_csv("credit_data.csv", sep = ",", header = None, na_values = "?")
cred_Data.head()

0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  202.0    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g   43.0  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  280.0  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  100.0    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  120.0    0  +

In [3]:
# : + for approved and - for not approved
# Changing the Classes to 1 & 0 from + & -

cred_Data.loc[cred_Data[15] == '+' , 15] = 1
cred_Data.loc[cred_Data[15] == '-' , 15] = 0
cred_Data.head()

0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  202.0    0  1
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g   43.0  560  1
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  280.0  824  1
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  100.0    3  1
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  120.0    0  1

In [4]:
# finding the number of null values in each of the features 

cred_Data.isnull().sum()

0     12
1     12
2      0
3      6
4      6
5      9
6      9
7      0
8      0
9      0
10     0
11     0
12     0
13    13
14     0
15     0
dtype: int64

In [5]:
# printing the shape and data types of each column

print("Shape of raw data set ",cred_Data.shape)
print("Data types of data set ",cred_Data.dtypes)

Shape of raw data set  (690, 16)
Data types of data set  0      object
1     float64
2     float64
3      object
4      object
5      object
6      object
7     float64
8      object
9      object
10      int64
11     object
12     object
13    float64
14      int64
15     object
dtype: object


In [6]:
# Dropping all the rows with na values

new_cred = cred_Data.dropna(axis = 0)
new_cred.shape


(653, 16)

In [7]:
# Verifying no null values exist

new_cred.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
dtype: int64

In [8]:
# Making dummy values from the categorical variables.

# Seperating the categorical variables to make dummy variables

cred_categorical = pd.get_dummies(new_cred[[0,3,4,5,6,8,9,11,12]])


In [9]:
# Seperating the numerical variables

cred_numerical = new_cred[[1,2,7,10,13,14]]

In [10]:
# Making the X variable which is a concatenation of categorical and numerical data

X = pd.concat([cred_categorical,cred_numerical], axis = 1)
print(X.shape)

# target feature as y

y = new_cred[15]
print(y.shape)
print(y.head())

(653, 46)
(653,)
0    1
1    1
2    1
3    1
4    1
Name: 15, dtype: object


In [11]:
# type of y is object, so sklearn cannot recognize its type.
# changing type of y as integer

y = y.astype("int")
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
685    0
686    0
687    0
688    0
689    0
Name: 15, Length: 653, dtype: int32


In [12]:
# Normalising the data sets
# Import library function

from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()

# Transforming with the scaler function
X_scaled = pd.DataFrame(min_max_scaler.fit_transform(X))

# Printing the output
X_scaled.head()

0    1    2    3    4    5    6    7    8    9   ...   36   37   38   39  \
0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0  0.0   
1  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0  0.0   
2  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0  0.0   
3  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  1.0  1.0  0.0  0.0   
4  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0   

         40        41        42        43      44       45  
0  0.271111  0.000000  0.043860  0.014925  0.1010  0.00000  
1  0.713016  0.159286  0.106667  0.089552  0.0215  0.00560  
2  0.170635  0.017857  0.052632  0.000000  0.1400  0.00824  
3  0.223492  0.055000  0.131579  0.074627  0.0500  0.00003  
4  0.101905  0.200893  0.060000  0.000000  0.0600  0.00000  

[5 rows x 46 columns]

In [13]:
# Splitting the data into train and test sets
# Importing library function

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=123)


In [14]:
# Defining the LogisticRegression function

from sklearn.linear_model import LogisticRegression

log_reg_model = LogisticRegression()

# Fitting a logistic regression model on the training set
log_reg_model.fit(X_train, y_train)

LogisticRegression()

In [15]:
# predictions on the test set

pred = log_reg_model.predict(X_test)
print("Accuracy of Logistic regression model prediction on test set: {:.2f}".format(log_reg_model.score(X_test, y_test)))

Accuracy of Logistic regression model prediction on test set: 0.89


In [16]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# Confusion Matrix for the model
print(confusion_matrix(y_test, pred))

# Classification report for the model
print(classification_report(y_test, pred))

[[93 14]
 [ 8 81]]
              precision    recall  f1-score   support

           0       0.92      0.87      0.89       107
           1       0.85      0.91      0.88        89

    accuracy                           0.89       196
   macro avg       0.89      0.89      0.89       196
weighted avg       0.89      0.89      0.89       196



###### We can see from the output, we achieved an accuracy level of 0.89 with the logistic regression model. we will try different methods of ensemble learning with simple methods

## Ensemble Model Using the Averaging Technique:

The averaging method creates an ensemble by combining the predictions of base learners and averaging the prediction probabilities.

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [18]:
# Defining the three base models. 

model1 = LogisticRegression(random_state = 20)
model2 = KNeighborsClassifier(n_neighbors = 5)
model3 = RandomForestClassifier(n_estimators = 500)

In [19]:
# Fitting all three models on the training data

model1.fit(X_train, y_train)
model2.fit(X_train, y_train)
model3.fit(X_train, y_train)

RandomForestClassifier(n_estimators=500)

In [20]:
# predicting the probabilities of each model on the test set

pred1 = model1.predict_proba(X_test)
pred2 = model2.predict_proba(X_test)
pred3 = model3.predict_proba(X_test)

In [21]:
# Calculating the ensemble prediction by averaging three base model predictions

ensemble_pred=(pred1 + pred2 + pred3)/3

In [22]:
# Displaying first 10 rows of the ensemble predictions

ensemble_pred[0:9,:]

# we have two probabilities for each example corresponding to each class.

array([[0.90516917, 0.09483083],
       [0.96396145, 0.03603855],
       [0.18357473, 0.81642527],
       [0.05083488, 0.94916512],
       [0.85873263, 0.14126737],
       [0.01209282, 0.98790718],
       [0.18589271, 0.81410729],
       [0.10031852, 0.89968148],
       [0.39451137, 0.60548863]])

In [23]:
#prediction output has two columns corresponding to each class - Printing the order of classes for each model

print(model1.classes_)
print(model2.classes_)
print(model3.classes_)

[0 1]
[0 1]
[0 1]


In [24]:
# getting the final predictions for each example from the output probabilities.
# The final prediction will be the class with the highest probability

pred = np.argmax(ensemble_pred, axis = 1)
pred

array([0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1],
      dtype=int64)

In [25]:
# generating confusion matrix

confusion_Matrix = confusion_matrix(y_test, pred)
print(confusion_Matrix)

[[96 11]
 [ 8 81]]


In [26]:
# generating classification report

from sklearn.metrics import classification_report
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.92      0.90      0.91       107
           1       0.88      0.91      0.90        89

    accuracy                           0.90       196
   macro avg       0.90      0.90      0.90       196
weighted avg       0.90      0.90      0.90       196



##### It is implemented the averaging technique for ensemble learning. As you can see from the classification report, we managed to improve the accuracy rate from 0.89 to 0.90 by averaging method. 

## Ensemble Model Using the Weighted Averaging Technique

The weighted averaging method was similar to the averaging method.The difference was in the way the predictions were combined. In this method, arbitrary weights were applied to the predictions of individual learners to get the final prediction.

In [27]:
#In the weighted averaging method, weights are assigned arbitrarily based on our judgment of each of the predictions
# weights are assigned  that the sum of all weights becomes 1 
# Calculating the ensemble prediction by applying weights for each prediction

ensemble_pred = (pred1 * 0.60 + pred2 * 0.20 + pred3 * 0.20)

In [28]:
# Displaying first 10 rows of the ensemble predictions
ensemble_pred[0:9,:]

array([[0.9229045 , 0.0770955 ],
       [0.9495306 , 0.0504694 ],
       [0.14323452, 0.85676548],
       [0.08830278, 0.91169722],
       [0.88651874, 0.11348126],
       [0.01936707, 0.98063293],
       [0.13940688, 0.86059312],
       [0.09897334, 0.90102666],
       [0.44372046, 0.55627954]])

In [29]:
# Printing the order of classes for each model
print(model1.classes_)
print(model2.classes_)
print(model3.classes_)

[0 1]
[0 1]
[0 1]


In [30]:
# Calculating the final predictions from the probabilities
# getting the final predictions for each example from the output probabilities using the np.argmax() function

pred = np.argmax(ensemble_pred, axis =1)
pred

array([0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1],
      dtype=int64)

In [31]:
# Generating confusion matrix

confusionMatrix = confusion_matrix(y_test, pred)
print(confusionMatrix)

[[94 13]
 [ 8 81]]


In [32]:
# Generating classification report

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.92      0.88      0.90       107
           1       0.86      0.91      0.89        89

    accuracy                           0.89       196
   macro avg       0.89      0.89      0.89       196
weighted avg       0.89      0.89      0.89       196



## Different Weights by Weighted Averaging Technique


In [33]:
# Calculating the ensemble prediction by applying weights for each prediction

ensemble_pred=(pred1 *0.70 + pred2 * 0.15  +pred3 * 0.15)

In [34]:
# Generating predictions from probabilities
pred = np.argmax(ensemble_pred,axis = 1)

In [35]:
# Generating confusion matrix
confusionMatrix = confusion_matrix(y_test, pred)
print(confusionMatrix)

[[94 13]
 [ 7 82]]


In [36]:
# Generating classification report

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.93      0.88      0.90       107
           1       0.86      0.92      0.89        89

    accuracy                           0.90       196
   macro avg       0.90      0.90      0.90       196
weighted avg       0.90      0.90      0.90       196



It is  implemented the weighted averaging technique for ensemble learning. We did two iterations with the weights. We saw that in the second iteration, where we increased the weight of the logistic regression prediction from 0.6 to 0.7, the accuracy actually improved from 0.89 to 0.90. 

# Max Voting Method

Max voting was a technique that arrived at final predictions based on the votes of the majority of the base learners.

In [65]:
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

# models
model1 = LogisticRegression(random_state= 20)
model2 = KNeighborsClassifier(n_neighbors= 6)
model3 = RandomForestClassifier(n_estimators=500)

In [66]:
# Defining the ensemble model using VotingClassifier
# voting is "hard, " which means that the output will be class labels and not probabilities
model = VotingClassifier(estimators=[( 'lr', model1),( 'knn', model2),( 'rf',model3)], voting= 'hard')

In [67]:
# Fitting the model on the training set

model.fit(X_train,y_train)

VotingClassifier(estimators=[('lr', LogisticRegression(random_state=20)),
                             ('knn', KNeighborsClassifier(n_neighbors=6)),
                             ('rf', RandomForestClassifier(n_estimators=500))])

In [68]:
# predicting accuracy score on the test set

model.score(X_test, y_test)

0.9081632653061225

In [69]:
# Generating the predictions on the test set

preds = model.predict(X_test)

In [70]:
# Confusion matrix for the test set

print(confusion_matrix(y_test, preds))

[[97 10]
 [ 8 81]]


In [71]:
# classification report for Max Voting Technique

print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       0.92      0.91      0.92       107
           1       0.89      0.91      0.90        89

    accuracy                           0.91       196
   macro avg       0.91      0.91      0.91       196
weighted avg       0.91      0.91      0.91       196



It is implemented the max voting technique for ensemble learning. As you can see from the classification report, the results are better than averaging method .This result is more balanced. The recall value for worthy customers is high, at 91 % for their credit application.

# Advanced Techniques for Ensemble Learning

I will implement some advanced techniques for ensemble learning such as Bagging, Boosting and Stacking/blending.

# Ensemble Learning with Bagging Method

Bagging : Multiple subsets of the data are created using bootstrapping. On each of these subsets of data, a base learner is fitted and the predictions generated. These predictions from all the base learners are then averaged to get the meta learner or the final predictions.

In [78]:
# Defining the base learner

from sklearn.ensemble import RandomForestClassifier
random_forest_model = RandomForestClassifier(random_state = 50)

In [93]:
# Creating the bagging meta learner
from sklearn.ensemble import BaggingClassifier
bagging_learner = BaggingClassifier(base_estimator = random_forest_model, n_estimators= 10, max_samples=0.6, max_features= 0.6)

In [94]:
# Fitting the model using the meta learner

model = bagging_learner.fit(X_train, y_train)

In [95]:
# Predicting on the test set using the model

pred = model.predict(X_test)

In [96]:
# Printing the confusion matrix
# from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, pred))

[[99  8]
 [12 77]]


In [97]:
# Printing the classification report

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.89      0.93      0.91       107
           1       0.91      0.87      0.89        89

    accuracy                           0.90       196
   macro avg       0.90      0.90      0.90       196
weighted avg       0.90      0.90      0.90       196



It is implemented ensemble learning using bagging method. As you can see from the classification report, we have a slightly lower result (0.90) than what we got from the max voting methods (0.91). However, looking at the results,
We can  see that  the recall value for identifying unworthy customers is around 93%, which means that only around 7% of the unworthy customers are wrongly classified as creditworthy.

# Ensemble Learning with Boosting Method

Boosting methods works in a sequential manner. It works on the principle of correcting the prediction errors of each base learner. The base learners are fit sequentially one after the other. A base learner tries to correct the error generated by the previous learner and this process continues until a superior meta learner is created. 

In [98]:
# Defining the base learner

model_logistic_reg = LogisticRegression(random_state = 50)

In [99]:
# Defining the boosting meta learner

from sklearn.ensemble import AdaBoostClassifier

boosting_model = AdaBoostClassifier(base_estimator = model_logistic_reg, n_estimators= 200)

In [101]:
# Fitting the model on the training set

fitted_model = boosting_model.fit(X_train, y_train)

In [102]:
# Getting the predictions from the boosting model

pred = fitted_model.predict(X_test)

In [103]:
# generating the confusion matrix

print(confusion_matrix(y_test, pred))

[[96 11]
 [ 8 81]]


In [104]:
# generating confusion matrix

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.92      0.90      0.91       107
           1       0.88      0.91      0.90        89

    accuracy                           0.90       196
   macro avg       0.90      0.90      0.90       196
weighted avg       0.90      0.90      0.90       196



It is implemented the ensemble learning model using boosting. As you can see from the classification report, we got very similar results (0.90) to the bagging method.The results are more balanced compared to result of the bagging method.(the recall values of 0.93 and 0.87 in bagging method). Here, we can see that the recall value of the unworthy customers (90%) and that of creditworthy customers (91%) are quite close to each other, which indicates a very balanced result.

# Ensemble Learning with Stacking Method

Stacking is an ensemble learning technique that combines multiple classification or regression models via a meta-classifier or a meta-regressor. The base level models are trained based on a complete training set, then the meta-model is trained on the outputs of the base level model as features

In [105]:
# Importing the meta learner (logistic regression) and base learners (knn and random forest)

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

base_learner_knn= KNeighborsClassifier(n_neighbors = 5)
base_learner_random_forest = RandomForestClassifier(random_state = 50)
meta_learner_log_reg = LogisticRegression(random_state = 50)

In [110]:
# Creating the StackingClassifier
# !pip install mlxtend 
from mlxtend.classifier import StackingClassifier

stackclf = StackingClassifier(classifiers=[base_learner_knn,base_learner_random_forest],
meta_classifier= meta_learner_log_reg)

In [111]:
# Fitting the model on the training set

main_model = stackclf.fit(X_train, y_train)

In [112]:
# Generating predictions on test set

pred = model.predict(X_test)

In [114]:
# Generating the confusion matrix

print(confusion_matrix(y_test, pred))

[[99  8]
 [12 77]]


In [115]:
# Generating the classification report

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.89      0.93      0.91       107
           1       0.91      0.87      0.89        89

    accuracy                           0.90       196
   macro avg       0.90      0.90      0.90       196
weighted avg       0.90      0.90      0.90       196



It is implemented the ensemble learning model using stacking. As you can see from the classification report, we did  get some improvements over the main model using the stacking classifier.

# Comparison of Advanced Ensemble Techniques and Picking the best Model

Initially for Bagging Method, I will define base learner and  meta learner, in the second part fitting the model, in the third part generating predictions and confusion matrix, in the last part printing classification report 

In [119]:
# Bagging Method
from sklearn.ensemble import BaggingClassifier 
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 

# Creating the bagging meta learner
base_lerner_log_reg = LogisticRegression(random_state = 50) 
bagging_learner = BaggingClassifier(base_estimator = base_lerner_log_reg, n_estimators= 15, max_samples = 0.8, max_features = 0.8) 

# Fitting the model using the meta learner 
model = bagging_learner.fit(X_train, y_train) 

# Predicting on the test set using the model 
pred = model.predict(X_test) 

print(confusion_matrix(y_test, pred)) 

print(classification_report(y_test, pred)) 

[[93 14]
 [ 7 82]]
              precision    recall  f1-score   support

           0       0.93      0.87      0.90       107
           1       0.85      0.92      0.89        89

    accuracy                           0.89       196
   macro avg       0.89      0.90      0.89       196
weighted avg       0.90      0.89      0.89       196



Output for Bagging Method

In [122]:
# Boosting Method

from sklearn.ensemble import BaggingClassifier 
from sklearn.ensemble import RandomForestClassifier 
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report  

base_learner_random_forest = RandomForestClassifier(random_state = 50) # base learner
boosting = AdaBoostClassifier(base_estimator = base_learner_random_forest, n_estimators = 100) # meta learner
model = boosting.fit(X_train, y_train) 
pred = model.predict(X_test) 
print(confusion_matrix(y_test, pred)) 
print(classification_report(y_test, pred)) 

[[96 11]
 [ 8 81]]
              precision    recall  f1-score   support

           0       0.92      0.90      0.91       107
           1       0.88      0.91      0.90        89

    accuracy                           0.90       196
   macro avg       0.90      0.90      0.90       196
weighted avg       0.90      0.90      0.90       196



Output for Boosting Method

In [125]:
# Importing the meta learner and base learners 
from sklearn.linear_model import LogisticRegression 
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.ensemble import RandomForestClassifier 
from mlxtend.classifier import StackingClassifier 
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 

base_learner_knn= KNeighborsClassifier(n_neighbors = 5)
base_learner_log_reg= RandomForestClassifier(random_state = 50)
meta_learner_random_forest = LogisticRegression(random_state = 50)

stack_clf = StackingClassifier(classifiers = [base_learner_knn, base_learner_log_reg,], meta_classifier= meta_learner_random_forest) 

model = stack_clf.fit(X_train, y_train) 
pred = model.predict(X_test) 

print(confusion_matrix(y_test, pred)) 
print(classification_report(y_test, pred))

[[94 13]
 [ 8 81]]
              precision    recall  f1-score   support

           0       0.92      0.88      0.90       107
           1       0.86      0.91      0.89        89

    accuracy                           0.89       196
   macro avg       0.89      0.89      0.89       196
weighted avg       0.89      0.89      0.89       196



Output for Stacking Method

I implemented on the credit card dataset with  three advanced ensemble techniques.(bagging, boosting and stacking) Based on the metrics, It is founded that boosting (0.90) has better results than bagging (0.89) and stacking (0.89). Therefore, select the boosting algorithm to boost the performance of our models because boosting algorithm generated more balanced results where the recall value of both creditworthy and not creditworthy customers (90% and 91%) is similar.